FROM oven/bun:1.2.23-alpine AS builder

WORKDIR /app

COPY . .

RUN bun install; bunx --bun vite build

FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
